name: 'Auto Fans Medal'

on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  auto_getting_traffic:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking'
        uses: actions/checkout@v2

      - name: 'Setting Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Auto Fans Medal'
        env:
          ACCESSKEY: ${{ secrets.ACCESSKEY }}      
        run: python main.py
